name: Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - ".Dockerfile"
      - ".github/workflows/publish.yaml"

jobs:
  build:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/mainframer
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: "latest"
